const router = require('express').Router();
const { authenticate } = require('../middlewares/auth.middleware');
const { supportMessageUpload } = require('../middlewares/upload.middleware');
const controller = require('../controllers/supportTicket.controller');
router.use(authenticate);
router.get('/', controller.list);
router.post('/', controller.create);
router.get('/settings', controller.settings);
router.get('/context', controller.context);
router.get('/metrics', controller.metrics);
router.put('/settings', controller.saveSettings);
router.put('/availability', controller.availability);
router.post('/claim', controller.claim);
router.get('/faq', controller.faq);
router.get('/faq/match', controller.match);
router.get('/supporting-documents', controller.catalog);
router.put('/supporting-documents', controller.saveCatalog);
router.get('/:ticketId', controller.read);
router.get('/:ticketId/requirements/:requirementId/history', controller.requirementHistory);
router.post('/:ticketId/messages', controller.uploadAccess, supportMessageUpload, controller.send);
router.post('/:ticketId/actions', controller.change);
router.post('/:ticketId/faq', controller.feedback);
module.exports = router;
